<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class GalleryController extends \TCG\Voyager\Http\Controllers\VoyagerBaseController
{
    public function store(Request $request)
    {
        dd($request);
        return parent::store($request); // TODO: Change the autogenerated stub
    }
}
